.github/pull_request_template.md
README.md
docs/classes/_speechly_d_.client.md
docs/interfaces/_speechly_d_.clientoptions.md
etc/browser-client.api.md
examples/index.html
package.json
src/speechly/client.ts
src/speechly/types.ts
src/websocket/client.ts
yarn.lock

Make WebSocket URL optional (default pointing towards `wss://api.speechly.com/ws`) and simplify WS URL building logic to `baseUrl / params` approach, instead of trying to utilise the URL API.
Most of the time (outside of testing) the client will use production Speechly API and simpler logic makes it easier to use TLS or non-TLS URLs.

Make WebSocket URL optional and change URL building logic

---

package.json
src/declarations.d.ts
src/speechly/client.ts
yarn.lock

Fix an issue with language codes like `en` or `fi` passing the validation in the client, but failing silently on the backend.
Since such language codes are considered invalid by the API, the validation was fixed on the client by explicitly checking the `languageCode-countryCode` format.
This PR also changed the dependency for language validation.
To make sure that invalid language configuration is indicated explicitly, instead of silently failing without an error.

Validate language against `languageCode-countryCode` format

---

examples/README.md
examples/public/index.html
examples/src/index.js

Fix indices rendering in the example, by switching to unordered lists for words and entities and indicating the entity range type (includes start index, but excludes end index).
Since the indices in the response are not guaranteed to be monotonically increasing and / or starting from 1, we should not rely on ordered lists to properly show those indices.

Fix indices rendering in the example

---

src/speechly/client.ts

This PR finalises the last pending segment when browser-client receives `stopped` event from the API, to make sure all tentative items are flushed.
If for some reason `segment_end` event from the API is received after the `stopped` event (or not received at all), it will cause the last segment in the context to never be finalised.
This PR addresses that issue by performing the check-and-finalise operation upon receiving the `stopped` event from the API.

Finalise last segment when context is stopped

---

src/speechly/client.ts

This reverts commit a9a80a5ece7fdeb2ad7006f95498336737fcd3fb.
Revert the finalisation of current segment upon receiving "context stopped" event.
The logic was causing some segment updates to be dropped, leading to bad experience.

Revert "Finalise last segment when context is stopped (#19)"

---

docs/interfaces/_index_d_.apiclient.md
docs/modules/_index_d_.md
etc/browser-client.api.md
src/microphone/browser_audio_processor.ts
src/microphone/browser_microphone.ts
src/microphone/sampler.ts
src/microphone/types.ts
src/speechly/client.ts
src/websocket/types.ts
src/websocket/websocket_client.ts

Improve resampling performance in Safari browsers with the following:
* Fix an issue in the lowpass filter generator, which was using wrong cutoff value
* Add custom buffer size value for WebKit browser (practically only means Safari) based on resample ratio
* Moved quantisation into the same loop as resampling
To achieve good audio quality in Safari browsers. Previously the audio quality was suffering from distortions, with the fixes the quality should be almost 100%. There still are occasional small distortions, but in general it's much better.
The quality issue seems to be caused by bad audio capture code in the engine itself, which seems to be performing very badly with default buffer size and in general is very sensitive to latency, hence the requirements to improve resampling / …

Improve resampling performance in Safari browsers

---

src/speechly/client.ts

Update default API URL, since it's been changed.
To make sure that the client uses correct endpoint address.

Update default API URL

---

README.md

This change makes the header a secondary element which helps the user to scan the contents of the document. Also some visual cleanup and fixing/adding of navigation links.
Previously the logo, description and the repo heading were all competing of the users attention by being visually equally prominent, making it hard for the user to parse this information. Also some url params were off and the navigation was kind of "lost" as it was squeezed between the two competing parties.

Improve readme header

---

common/changes/@speechly/browser-ui/browser-ui-embedded-doc-update_2021-11-15-15-22.json
common/changes/@speechly/browser-ui/browser-ui-embedded-doc-update_2021-11-15-15-24.json
libraries/browser-ui/package.json
libraries/browser-ui/src/assets/extras.html
libraries/browser-ui/src/assets/index.html

Changed links to point to unpkg.com in embedded docs.
Deprecating GitHub pages CDN deployment.

Browser UI/embedded doc update and 5.0.1 publish for unpkg

---

common/config/rush/pnpm-lock.yaml
demos/ecommerce-checkout/package.json
demos/fashion-ecommerce/package.json
demos/flight-booking/package.json
demos/smart-home/package.json
demos/speech-to-text/package.json

Update demo-navigation dependency that includes correct demo paths as well as fixes for Safari
It was borken

Update @speechly/demo-navigation 0.1.29 → 0.1.30

---

README.md

Rearranged readme chapters to address repo content first. Learn more moved toward the bottom.
To make the README a better landing page for demo navigation's "View on GitHub" button.

Rearranged readme chapters to state repo content first

---

common/changes/@speechly/react-ui/release-react-ui-2.1.3_2021-11-18-13-52.json
common/changes/@speechly/react-ui/release-react-ui-2.1.3_2021-11-18-13-55.json
libraries/react-ui/package.json

react-ui release compatible with browser-ui 5.x
Due to migration to Rush monorepo the internal structure of browser-ui package was changed. React-ui had internal browser-ui >= 4.x dependency, which didn't work with the browser-ui 5.x

Release/react UI 2.1.3

---

common/changes/@speechly/react-client/fix-react-client-ssr--create-speechly-at-dom-mount_2021-12-28-09-49.json
libraries/react-client/package.json
libraries/react-client/src/context.tsx

- Postpone Speechly creation to DOM mount time to prevent it from happening on the server-side.
- Also fixes npm packs by explicitly including `dist/` folder in package (currently `dist/` is gitignored, so publishing to npm is currently bork)
To enable Speechly with frameworks that use server side rendering (SSR). With sister PR https://github.com/speechly/speechly/pull/113 this PR enables Speechly's React tools on frameworks like Nextjs.
Currently using Speechy with Nextjs always fails with `webWorkerController.js 63:22 - ReferenceError: Blob is not defined` when attempting to use `SpeechProvider` from `react-client` package. React-client internally initialized browser-client in SpeechProvider class constructor, which failed as browser APIs are unavailable on server side. After this PR, …

Initialize Speechly on DOM mount instead of constructor to fix server-side rendering problems

---

common/changes/@speechly/react-ui/feature-react-ui-dynamic-browser-ui-import_2021-12-27-15-37.json
demos/fashion-ecommerce/package.json
demos/smart-home/package.json
libraries/react-ui/package.json
libraries/react-ui/src/components/BigTranscript.tsx
libraries/react-ui/src/components/ErrorPanel.tsx
libraries/react-ui/src/components/PushToTalkButton.tsx
libraries/react-ui/src/components/TranscriptDrawer.tsx
libraries/react-ui/src/declarations.d.ts

Dynamic import of browser-ui custom elements in react-ui.
(Also updates `styled-components` to 5.3.3 to fix `rush build`, which is failing due to missing `react-is` dependency)
To enable Speechly with frameworks like Nextjs that use server side rendering (SSR).
Without this, Nextjs always fails when using react-ui package. The problem seems to be due to Next’s server-side rendering (SSR) of pages. React-ui internally uses custom elements aka “web components” provided by browser-ui. Next.js (like many frameworks) lack SSR of web components and it seems to drop the package and hence throw `module not found`.
This fix per a method outlined here: https://dev.to/swyx/how-to-use-web-components-with-next-js-and-typescript-4gg1
This PR is a partial fix for enabling Speechly on Nextjs. react-ui …

Fix react-ui on Nextjs: Use dynamic browser-ui imports for SSR compability

---

demos/fashion-ecommerce/config/voice-interface.yaml

When users utter one-word-utterances such as just "medium", "large", "popular" etc. the system has hard time to identify these as "sizes" or "sort" entities, respectively.
To get more robust results.

Enable strict NLU 

---

demos/fashion-ecommerce/config/voice-interface.yaml

Revert fashion demo to use legacy ("fast") intent detector.
The new LSTM based intent detector does not do very well on this configuration.

use fast intent detector

---

common/changes/@speechly/browser-client/fix-stop-context-errors_2022-05-10-07-50.json
libraries/browser-client/src/client/browser_client.ts

Catch the error thrown from `CloudDecoder` and log a warning instead of throwing the error upwards.
If the state management is off for any reason (WS disconnect etc), it should be easy to "catch up". This change makes it easy, as the only effect is a warning log.
The other way to manage state outside the client is to subscribe to `onStateChange`, which will push the state changes to the caller.

Do not throw Error if stopping a stopped context

---

common/changes/@speechly/browser-client/fix-fetch-token_2022-05-30-06-34.json
libraries/browser-client/src/client/decoder.ts

`fetchToken` function's 5th parameter has a default value `fetch`, that is not used for some reason. Give it explicitly when calling the function.
Steps to reproduce:
1. Run `localStorage.clear()` in browser console to delete current token.
2. Start *examples/browser-client-example*
3. Click Connect
4. Observe error `TypeError: fetcher is not a function`
After this change, this error does not happen and browser-client can connect normally.

browser-client: provide explicitly fetcher function

---

common/changes/@speechly/browser-client/fix-sample-rate-on-ff-and-safari_2022-06-14-13-28.json
libraries/browser-client/src/client/browser_client.ts
libraries/browser-client/src/client/decoder.ts

- Prevented microphone sample rate from resetting to default upon call to startStream.
- Firefox and Safari were sending 44kHz mic data instead of downsampling it to 16kHz. As a result no valid ASR was sent back.

Fix/sample rate on Firefox and Safari

---

common/changes/@speechly/browser-client/langma-patch-1_2022-06-28-10-02.json
libraries/browser-client/README.md

Add the missing `await` from client's attach call, making the following `start()` call use the initialised AudioProcessor properly.
Fixes https://github.com/speechly/speechly/issues/210.

Fix HTML code example

---

common/changes/@speechly/browser-client/fix-use-history-without-vad_2022-08-11-18-02.json
libraries/browser-client/src/client/browser_client.ts
libraries/browser-client/src/client/types.ts

- Stream options contains an internal autostart flag
- Only autostarted streaming to AudioProcessor is automatically stopped.
- Fixed honoring user-initiated startStream(). It should keep streaming audio to AudioProcessor to be able to send historyFrames upon start(). The stream was incorrectly paused upon call to stop(), which should only happen for automatically started streams when VAD is not in use.

Use history without VAD

---

common/changes/@speechly/browser-client/update-non-streaming-nlu-flag_2022-10-11-13-01.json
libraries/browser-client/src/client/types.ts
libraries/browser-client/src/websocket/worker.test.ts
libraries/browser-client/src/websocket/worker.ts

Once the non-streaming NLU variant is enabled in the back-end, these changes should allow specifying at inference time which NLU variant to use.

add non_streaming_nlu flag to ContextOptions

---

common/changes/@speechly/browser-client/fix-browser-client-click-spam_2022-10-13-07-58.json
common/changes/@speechly/react-client/fix-browser-client-click-spam_2022-10-13-09-55.json
libraries/browser-client/docs/classes/client.BrowserClient.md
libraries/browser-client/docs/interfaces/client.ContextOptions.md
libraries/browser-client/docs/modules/client.md
libraries/browser-client/src/audioprocessing/AudioProcessor.ts
libraries/browser-client/src/audioprocessing/EnergyThresholdVAD.ts
libraries/browser-client/src/client/browser_client.ts
libraries/browser-client/src/client/decoder.ts
libraries/browser-client/src/client/types.ts
libraries/browser-client/src/microphone/browser_microphone.ts
libraries/browser-client/src/websocket/types.ts
libraries/browser-client/src/websocket/worker.test.ts
libraries/browser-client/src/websocket/worker.ts
libraries/react-client/docs/classes/context.SpeechProvider.md
libraries/react-client/docs/interfaces/context.SpeechContextState.md
libraries/react-client/src/context.tsx

*Problem*: Calling `BrowserClient.start()` and `stop()` quickly multiple times resulted in `[Decoder] Unable to complete startContext: Expected Connected state, but was in Active` error.
- *Cause 1*: `BrowserClient.StopStream()` and `CloudDecoder.stopStream()` were operating outside their area of responsibilities and directly manipulated context active state. This is supposed to be the responsibility of `BrowserClient.Stop()` which has an action queue to protect against concurrent use and rapid state changes.
- *Cause 2*: `CloudDecoder.stopContext()` did not wait for the network request to complete.
Both of the causes contributed to `CloudDecoder.state` not being in sync with what was expected by concurrency-protected blocks in `BrowserClient.start()` and `CloudDecoder.stop()`.
- *Fixes*: …

Fix/BrowserClient errors when rapidly clicking hold-to-talk button

---

common/changes/@speechly/browser-ui/fix-rush-check_2022-11-14-13-59.json
common/changes/@speechly/react-client/fix-rush-check_2022-11-14-13-59.json
common/changes/@speechly/react-ui/fix-rush-check_2022-11-14-13-59.json
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
examples/react-ui-example/package.json
libraries/browser-ui/package.json
libraries/logkit/package.json
libraries/react-client/package.json
libraries/react-ui/package.json

- Harmonize project dependencies. `rush check` should now happily say `Found no mis-matching dependencies!`
- Bump `browser-ui` and `react-ui` versions to trigger npm patch releases. There hasn't been a release in 5 months and they are lacking latest `browser-client` robustness improvements.
- Release latest (unreleased) changes to npm

Fix/rush check, patch releases

---

common/changes/@speechly/browser-client/fix-update-browserslist-and-deps_2022-11-16-10-21.json
common/changes/@speechly/browser-ui/fix-update-browserslist-and-deps_2022-11-15-14-39.json
common/changes/@speechly/react-ui/fix-update-browserslist-and-deps_2022-11-15-14-39.json
common/config/rush/pnpm-lock.yaml
examples/react-ui-example/src/App.tsx
libraries/browser-client/package.json
libraries/browser-client/tsconfig.json
libraries/browser-ui/package.json
libraries/browser-ui/rollup.config.js
libraries/browser-ui/src/index.ts
libraries/browser-ui/src/intro-popup.svelte
libraries/browser-ui/tsconfig.json
libraries/react-ui/src/declarations.d.ts

- Ran `rush update --full` to bring dependencies, including caniuse-lite and browserlist up-to-date.
- Fixed TypeScript declarations in `browser-client` and `browser-ui` which were pointing to incorrect folder.
- Fixed some code rot. Re-added browser-ui `demomode.js` to `browser-ui` package.
- Publish `browser-client`, `browser-ui` and `react-ui` patches to npm.
- Fix demo deployment GitHub action, broken by browserlist warnings.

Fix/update browserslist, type declarations and deps

---

CONTRIBUTING.md
README.md
common/changes/@speechly/browser-client/fix-example-links_2023-01-30-17-23.json
common/changes/@speechly/react-client/fix-example-links_2023-01-30-17-23.json
examples/browser-client-example/README.md
examples/react-client-example/README.md
libraries/browser-client/README.md
libraries/browser-client/package.json
libraries/react-client/README.md
libraries/react-client/package.json

- Fix old/broken links in browser/react client readmes
- Improve react/browser client examples readmes
- Unify taxonomy, stylize text and improve examples getting started
We were linking to old repos or obsolete urls. Also the examples instructions needed some improvement.

Fix example links

---

examples/android-decoder-example/SpeechlyDecoderTest/src/main/java/com/speechly/decodertest/SpeechlyHandler.java
examples/c-decoder-example/c_decoder_test.c

This PR:
- removes tflite dependency from Android example
- sets decoder block size multiplier in Android and C examples

android example fix

---

demos/analyzer/package.json
demos/analyzer/src/App.css
demos/analyzer/src/App.tsx
demos/analyzer/src/components/Dialog.css
demos/analyzer/src/components/Form.css
demos/analyzer/src/components/SegmentItem.css
demos/analyzer/src/index.css
demos/transcription/package.json
demos/transcription/src/App.css
demos/transcription/src/App.tsx
demos/transcription/src/index.css

- Refactor microphone implementation in **transcription** and **analyzer** demos. Use `microphone` object available through react-client instead of the `ourMic` implementation.
- Set latest recording as "selected" item.
- Update styles, mainly empty state and font smoothing/weights.
React-client version `2.2.4` fixed the undefined microphone object, making it possible to use it instead of our custom microphone implementation.

Refactor microphone implementation in demos

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

Explicitly set a `preferredVersion` for `browserslist` in `common-versions.json` to get rid of the annoying `caniuse-lite` warnings during build phase.

Fix caniuse-lite warnings

---

demos/moderation/src/components/SegmentItem.tsx
demos/moderation/src/components/Tooltip.css
demos/moderation/src/components/Tooltip.tsx

An attempt to clarify the flagged labels to the user:
- Flagged labels have a hover tooltip that explains that the label in question was flagged and that each label has their own threshold for flagging.
- Non-flagged labels do not have a tooltip

Add tooltip for flagged labels
