examples/package.json, examples/public/index.html, examples/src/index.js, examples/yarn.lock, src/speechly/client.ts, src/speechly/segment.ts
* Fix intent event handling in the Client
* Protect finalised intent from being overwritten
* Add intent handling to demo
Intent handling was not showcased and not working properly. With this change the intent handling will be fixed and showcased in the demo.
=> Fix intent event handling and add intent handling to demo

.github/workflows/pull_requests.yml, package.json, src/declarations.d.ts, src/microphone/microphone.ts
* Fix crash in Safari due to missing window.AudioContext
* Set up GitHub actions on PRs to master
* In order to make the client work properly in Safari
* So that we can at least verify that the builds are passing
=> Fix crash in Safari due to missing window.AudioContext

.github/workflows/pull_request.yml, .github/workflows/release.yml, .prettierrc, CONTRIBUTING.md, README.md, config/webpack.config.js, package.json
Add GitHub action for automatically publishing releases to NPM registry. Also expand the contribution guide and move it out of the README.
To make contributions and publishing simpler.
=> Add GitHub action for releases and a contribution guide

package.json, src/microphone/browser_audio_processor.ts, src/microphone/browser_microphone.ts, src/microphone/downsampler.ts, src/speechly/client.ts
* Split microphone audio handling into microphone handler and audio processor
* Improve the performance of audio processing code
* Refactored code can now be unit-tested (at least partially, since unit-testing audio API is not quite possible)
* Audio processing improvements should hopefully fix issues in some corner-cases in iOS Safari (to be tested).
Can be verified by running the example in the browser of your choice - https://github.com/speechly/browser-client-example.
=> Improve and refactor microphone audio handling

src/microphone/browser_audio_processor.ts
Make sure that when requesting specific sample rate from audio context, the client also requests the same sample rate from the microphone stream.
Since the latter is not supported in all browsers, the whole native resampling logic now has to check for supported media constraints.
Unfortunately this does lead to the code being pretty hairy, but I'll think about streamlining it later, since current implementation crashes in some desktop Firefox configurations.
Current implementation is crashing in certain desktop Firefox configurations. Could be related to the new "resist fingerprinting" feature in the latest Firefox, but most importantly Firefox does not support connecting nodes with different sample rates together - `Connecting AudioNodes from AudioContexts with different sample-rate is …
=> Implement proper native resampling logic

README.md, docs/interfaces/_index_d_.clientoptions.md, etc/browser-client.api.md, src/speechly/client.ts, src/speechly/types.ts
Set en-US as a default language for the Client.
=> Set default language to en-US

src/speechly/client.test.ts, src/speechly/client.ts
Add delay after releasing the microphone button
=> Add delay to context stops

etc/browser-client.api.md, package.json, src/speechly/client.ts, src/websocket/types.ts, src/websocket/webWorkerController.ts, src/websocket/worker.ts
=> add switchContext

package.json, src/websocket/worker.ts
=> reconnect on websocket close

demos/ecommerce-checkout/README.md, demos/flight-booking/README.md, demos/speech-to-text/README.md
Added a brief description of demos to demo READMEs.
A basic intro and overview of demonstrated features
=> Restored demo descriptions in respective READMEs

README.md
Changed "spoken language understanding" to "Spoken Language Understanding" 
To align with our other online assets
=> spoken language understanding -> Spoken Language Understanding

.github/workflows/deploy-fashion.yaml, .github/workflows/deploy-smart-home-demo.yaml, .github/workflows/validate-ecommerce-checkout.yaml, .github/workflows/validate-fashion.yaml, .github/workflows/validate-smart-home-demo.yaml
Add Github Action workflows for evaluating fashion, smart-home and ecommerce-checkout demos.
To make maintaining said demos easier, as well as to demonstrate how speechly CLI can be used as part of CI pipelines.
=> ci workflows for fashion, smart-home and ecom-checkout

common/changes/@speechly/react-voice-forms/fix-issue_with_dates_2021-12-01-08-05.json, libraries/react-voice-forms/src/components/VoiceDatePicker.tsx
Fixes an issue where date can appear to be wrong due to difference in UTC versus local timezone.
To achieve expected behaviour.
=> Fix an issue where date can be wrong due to timezones

demos/fashion-ecommerce/config/ground_truth.txt, demos/fashion-ecommerce/config/test_utterances.txt, demos/flight-booking/config/ground_truth.txt, demos/flight-booking/config/test_utterances.txt, demos/smart-home/config/config.yaml, demos/smart-home/config/ground_truth.txt, demos/smart-home/config/test_utterances.txt
Add test utterances for flight booking for CI evaluation.
We want to ensure that no broken configs are deployed to production version of flight-booking.
=> add test and ground truth utterances for flight booking

demos/fashion-ecommerce/config/category.csv
=> fashion updates

demos/smart-home/config/config.yaml
Add "all", "all lights" to the devices list.
Add "close" to the command list.
Add "up" and "down" to support utterances such as "turn up the lights" or "turn down the lights".
=> config updates

demos/fashion-ecommerce/config/category.csv, demos/fashion-ecommerce/config/voice-interface.yaml
Lookup updates (category) and some small config updates.
Regular demo update.
=> lookup and config updates

demos/fashion-ecommerce/config/filter.csv, demos/fashion-ecommerce/config/voice-interface.yaml
=> update fashion demo config

demos/fashion-ecommerce/config/voice-interface.yaml
=> refine open intents list

demos/fashion-ecommerce/config/brand.csv, demos/fashion-ecommerce/config/category.csv, demos/fashion-ecommerce/config/colors.csv, demos/fashion-ecommerce/config/ground_truth.txt, demos/fashion-ecommerce/config/sex.csv, demos/fashion-ecommerce/config/sizes.csv, demos/fashion-ecommerce/config/sort.csv, demos/fashion-ecommerce/config/test_utterances.txt
regular fashion look-ups update
=> update fashion look-ups

demos/fashion-ecommerce/config/brand.csv, demos/fashion-ecommerce/config/category.csv, demos/fashion-ecommerce/config/sort.csv, demos/fashion-ecommerce/config/voice-interface.yaml, demos/smart-home/config/config.yaml, demos/smart-home/config/ground_truth.txt, demos/smart-home/config/test_utterances.txt
Fashion demo and smart home demo maintenance
=> Demo maintenance: update fashion lookups and config, update smart home config

libraries/browser-client/package.json, libraries/browser-client/src/client/browser_client.ts
Minor fixes to the existing PR / repo
a) Without the rollup package, it didn't build for me.
b) A few console logs weren't wrapped with a debug mode check
=> Minor fixes for "Feature/split microphone uploader"

demos/fashion-ecommerce/config/brand.csv, demos/fashion-ecommerce/config/category.csv, demos/fashion-ecommerce/config/colors.csv, demos/fashion-ecommerce/config/sort.csv, demos/fashion-ecommerce/data/filter-config.csv
Regular fashion demo maintenance
Keep it updated based on users' expectations
=> update csv files, new synonyms

common/changes/@speechly/react-client/config-update_2022-05-12-15-12.json, demos/fashion-ecommerce/config/brand.csv, demos/fashion-ecommerce/config/category.csv, demos/fashion-ecommerce/data/filter-config.csv, libraries/react-client/package.json
Update lookups, add some synonyms
=> Config update

demos/ecommerce-checkout/package.json, demos/fashion-ecommerce/package.json, demos/flight-booking/package.json, demos/moderation/package.json, demos/smart-home/package.json, demos/speech-to-text/package.json, demos/voice-search/package.json, examples/next-js-example/package.json, examples/react-ui-example/package.json, examples/react-voice-forms-example/package.json
- Demos to use latest react-client and react-ui
- Use version of react-client that fixes Firefox and Safari issues
=> Demos to use latest react-client and react-ui

demos/analyzer/src/App.tsx, demos/analyzer/src/Waveform.tsx
Ensure that labels for each audio region are kept in correct order.
=> use explicit index for each waveform region

demos/analyzer/src/App.css, demos/analyzer/src/App.tsx, demos/analyzer/src/Waveform.tsx, demos/transcription/src/App.css, demos/transcription/src/App.tsx, demos/transcription/src/Waveform.tsx
Add word level highlighting for played audio to both analyzer and transcription demos. Works in the same fashion as on the moderation demo. See video below for a demonstration:
https://user-images.githubusercontent.com/2579244/213799502-0d299ab4-524c-485f-be72-ae6af2c7ec32.mov
=> Highlight played words in transcription/analyzer demos

common/config/rush/pnpm-lock.yaml, demos/analyzer/package.json, demos/ecommerce-checkout/package.json, demos/fashion-ecommerce/package.json, demos/flight-booking/package.json, demos/moderation/package.json, demos/smart-home/package.json, demos/speech-to-text/package.json, demos/transcription/package.json, demos/voice-search/package.json
Upgraded demo-navigation npm package version for all demos.
The new demo-navigation package version includes demo route (page view event) tracking.
=> Upgraded demo-navigation package version for all demos

common/config/rush/pnpm-lock.yaml, demos/analyzer/package.json, demos/ecommerce-checkout/package.json, demos/fashion-ecommerce/package.json, demos/flight-booking/package.json, demos/moderation/package.json, demos/smart-home/package.json, demos/speech-to-text/package.json, demos/transcription/package.json, demos/voice-search/package.json
Upgraded Speechly's demo-navigation NPM package to v0.2.12.
The new version of the demo-navigation package includes fixes to how URLs are processed in the tracking functions.
=> Upgraded demo-navigation to v0.2.12

common/changes/@speechly/browser-client/fix-client-readmes_2023-02-17-13-38.json, examples/react-client-example/README.md, libraries/browser-client/README.md
=> Fix browser-client readme

common/config/rush/pnpm-lock.yaml, demos/analyzer/package.json, demos/ecommerce-checkout/package.json, demos/fashion-ecommerce/package.json, demos/flight-booking/package.json, demos/moderation/package.json, demos/smart-home/package.json, demos/speech-to-text/package.json, demos/transcription/package.json, demos/voice-search/package.json
Updated the demo-navigation package version.
The new version includes pageview tracking for the new GA4 property.
=> Updated demo-navigation version

demos/analyzer/src/components/Waveform.tsx
Don't show the tone of voice info if:
- `showTOV` is false
- `toneOfVoice` array is empty
=> Hide tone of voice if empty array

examples/android-decoder-example/README.md, examples/ios-decoder-example/README.md
- Add section about how to obtain both model bundle and library
- Fix broken image links
Better experience
=> Update decoder readmes and fix broken images

common/changes/@speechly/react-client/fix-rc-mic_2023-05-09-07-15.json, libraries/react-client/src/context.tsx
This PR fixes the issue described here https://github.com/speechly/speechly/issues/304#issuecomment-1539529613
=> Fix microphone export in react-client

examples/react-client-example/package-lock.json, examples/react-client-example/package.json
Update react-client to version 2.2.4 in react-client-example
=> Update react-client in example

examples/ios-client-example/RepoFiltering.xcodeproj/project.pbxproj, examples/ios-client-example/RepoFiltering.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Update dependencies in iOS example.
=> Update ios example dependencies
